---

- name: install gpg
  apt:
    pkg: gpg
    state: present
    install_recommends: no

- name: fetch kea apt key
  shell:
    cmd: wget -O - https://dl.cloudsmith.io/public/isc/kea-2-2/gpg.A8CB727C62565FF8.key | gpg --dearmor -o /usr/share/keyrings/isc-kea-2-2-archive-keyring.gpg
    creates: /usr/share/keyrings/isc-kea-2-2-archive-keyring.gpg
    warn: no

- name: add kea apt repository
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/isc-kea-2-2-archive-keyring.gpg] https://dl.cloudsmith.io/public/isc/kea-2-2/deb/debian bullseye main
    state: present
    update_cache: yes

- name: install kea
  apt:
    pkg: isc-kea-dhcp4-server
    state: present

- name: configure kea
  template:
    src: kea-dhcp4.conf.j2
    dest: /etc/kea/kea-dhcp4.conf
    owner: _kea
    group: root
    mode: '0644'
  notify: reload kea
  tags: conf

- name: start kea
  service:
    name: isc-kea-dhcp4-server
    state: started
    enabled: yes

- name: install firewall rules for dhcp
  template:
    src: dhcp.nft.j2
    dest: /etc/nftables/in.d/dhcp.nft
    owner: root
    group: root
    mode: '0644'
  notify: reload firewall
  tags: firewall
