---

- name: reload firewall
  service:
    name: nftables
    state: reloaded

# NOTE: The remaining handler makes sure that the interfaces are
# reconfigured on the Wireguard level when the configuration changes.
# However, if the IP addresses on an interface change when the interface
# is already up, the administrator will need to manually intervene.
#
# These two commands must be run in one go, since the wg-quick reload
# unsets the private key. If we are connecting over the VPN link being
# modified and we run these in separate handlers, then the link will go
# down after the first and we won't be able to connect to reset the
# private key and bring the link back up!
- name: reload wireguard interfaces
  shell: |
    systemctl reload wg-quick@{{ item.name }}
    wg set {{ item.name }} private-key /etc/wireguard/private_key
  loop: '{{ wg_ifs }}'
