---

internal_ipv4: 172.23.71.50
internal_ipv6: fda0:281f:5817::12

loopback_if: loopback-addrs
manual_backbone_ifs: [eno1, us-beh-bb-1]
access_ifs: [guests]
protected_ifs:
- name: prt-guests
  allowed_nets:
  - '{{ internal_net_v4 }}'
  - '{{ internal_net_v6 }}'
advertised_ifs: [guests, prt-guests]

router_site_role: clos_leaf_with_l2_spine
clos_leaf_as: 4200000000
clos_to_spines:
  core1:
    ipv6: fe80::92fb:a6ff:fe1d:d75a
    if: eno1
clos_to_vms:
  ipv6: fda0:281f:5817:120::1
  if: guests
clos_to_backbone_vm:
  ipv6: fe80::5054:ff:fe80:5d7e
  if: us-beh-bb-1
