---

internal_ipv4: 172.23.71.51
internal_ipv6: fda0:281f:5817::13

loopback_if: loopback-addrs
manual_backbone_ifs: [eno1]
access_ifs: [guests]
advertised_ifs: [guests]

router_site_role: clos_leaf_with_l2_spine
clos_leaf_as: 4200000001
clos_to_spines:
  core1:
    ipv6: fe80::1e69:7aff:fe45:4100
    if: eno1
clos_to_vms:
  ipv6: fda0:281f:5817:130::1
  if: guests
