---

internal_ipv4: 172.23.71.50
internal_ipv6: fda0:281f:5817::12

docker_net_v4: 192.168.18.0/24
docker_net_v6: fda0:281f:5817:12::/64

loopback_if: loopback-addrs
manual_backbone_ifs: [int-oxc]
manual_access_ifs: [dbr-general]
home_ifs: [eth0]
endpoint_ifs: [dbr-general]

ospf_manual_ifs:
- name: int-oxc
  type: broadcast
  cost: 10

rip_ifs: [eth0]

bgp_as: 4200000002
bgp_manual_peers:
- name: int_svc
  template: service_advertisement
  neighbor: range {{ docker_net_v6 }}
  as: 4200000000
