{
 "title": "BGP per-host details",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "up{job=\"bird\"}"
    }
   },
   { "name": "ip_version", "query": "4,6" }
  ]
 },
 "panels": [
  {
   "title": "BGP statistics",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(bird_protocol_up{name=~\"dn42_.+\",proto=\"BGP\",instance=\"$instance\",ip_version=\"$ip_version\"}) or vector(0)",
     "legendFormat": "DN42 peers"
    },
    {
     "expr": "count(bird_protocol_up{name=~\"int_.*\",name!~\"int_svc.*\",proto=\"BGP\",instance=\"$instance\",ip_version=\"$ip_version\"}) or vector(0)",
     "legendFormat": "Internal peers"
    },
    {
     "expr": "count(bird_protocol_up{name=~\"int_svc_.*\",proto=\"BGP\",instance=\"$instance\",ip_version=\"$ip_version\"}) or vector(0)",
     "legendFormat": "Internal service peers"
    },
    {
     "expr": "sum(bird_protocol_prefix_preferred_count{proto=\"BGP\",instance=\"$instance\",ip_version=\"$ip_version\"})",
     "legendFormat": "Preferred  prefixes"
    }
   ]
  },
  {
   "title": "Preferred prefixes per non-service peer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "bird_protocol_prefix_preferred_count{proto=\"BGP\",name=~\"(dn42|int_).+\",name!~\"int_svc.*\",instance=\"$instance\",ip_version=\"$ip_version\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Prefixes",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "bird_protocol_prefix_import_count{proto=\"BGP\",instance=\"$instance\",ip_version=\"$ip_version\",name!=\"int_svc\"}"
    },
    {
     "expr": "bird_protocol_prefix_filter_count{proto=\"BGP\",instance=\"$instance\",ip_version=\"$ip_version\",name!=\"int_svc\"}"
    },
    {
     "expr": "bird_protocol_prefix_preferred_count{proto=\"BGP\",instance=\"$instance\",ip_version=\"$ip_version\",name!=\"int_svc\"}"
    },
    {
     "expr": "bird_protocol_prefix_export_count{proto=\"BGP\",instance=\"$instance\",ip_version=\"$ip_version\",name!=\"int_svc\"}"
    }
   ]
  },
  {
   "title": "Updates and withdraws received per non-service peer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "c/m" } },
   "targets": [
    {
     "expr": "irate(bird_protocol_changes_update_import_receive_count{name=~\"(dn42|int_).+\",name!~\"int_svc.*\",proto=\"BGP\",instance=\"$instance\",ip_version=\"$ip_version\"}[$__rate_interval])*60+irate(bird_protocol_changes_withdraw_import_receive_count{name=~\"(dn42|int_).+\",name!~\"int_svc.*\",proto=\"BGP\",instance=\"$instance\",ip_version=\"$ip_version\"}[$__rate_interval])*60",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Updates and withdraws sent per non-service peer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "c/m" } },
   "targets": [
    {
     "expr": "irate(bird_protocol_changes_update_export_accept_count{name=~\"(dn42|int_).+\",name!~\"int_svc.*\",proto=\"BGP\",instance=\"$instance\",ip_version=\"$ip_version\"}[$__rate_interval])*60+irate(bird_protocol_changes_withdraw_export_accept_count{name=~\"(dn42|int_).+\",name!~\"int_svc.*\",proto=\"BGP\",instance=\"$instance\",ip_version=\"$ip_version\"}[$__rate_interval])*60",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}