{
 "title": "Host resources",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "up{job=\"node\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "$instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (mode) (irate(node_cpu_seconds_total{instance=~\"$instance\",mode!=\"idle\"}[$__rate_interval]))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "node_load5{instance=~\"$instance\"}",
     "legendFormat": "5-minute load average"
    },
    {
     "expr": "count(count without (mode) (node_cpu_seconds_total{instance=~\"$instance\"}))",
     "legendFormat": "Total CPUs"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"}-node_memory_MemFree_bytes{instance=~\"$instance\"}-node_memory_Buffers_bytes{instance=~\"$instance\"}-node_memory_Cached_bytes{instance=~\"$instance\"}-node_memory_SReclaimable_bytes{instance=~\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$instance\"}+node_memory_SReclaimable_bytes{instance=~\"$instance\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$instance\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{instance=~\"$instance\",device!=\"loopback-addrs\"}[$__rate_interval]))",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{instance=~\"$instance\",device!=\"loopback-addrs\"}[$__rate_interval]))",
     "legendFormat": "Transmit"
    }
   ]
  }
 ]
}