{
 "title": "Overview",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Administrative statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hosts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"node\"})",
     "legendFormat": "Hosts total"
    },
    {
     "expr": "sum(up{job=\"node\"})",
     "legendFormat": "Hosts up"
    }
   ]
  },
  {
   "title": "APT upgrades",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (count by (instance) (apt_upgrades_pending>0)) or vector(0)",
     "legendFormat": "Hosts with upgrades"
    },
    { "expr": "sum (apt_upgrades_pending)", "legendFormat": "Upgrades pending" }
   ]
  },
  {
   "title": "DN42 peers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(bird_protocol_up{proto=\"BGP\",name=~\"dn42_.+\"})/2 or vector(0)",
     "legendFormat": "DN42 peers configured"
    },
    {
     "expr": "sum(bird_protocol_up{proto=\"BGP\",name=~\"dn42_.+\"})/2 or vector(0)",
     "legendFormat": "DN42 peers up"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "External data usage over range",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{device=\"eth0\"}[$__range]) + increase(node_network_transmit_bytes_total{device=\"eth0\"}[$__range])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "DN42 data usage over range",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (increase(node_network_receive_bytes_total{device=~\"dn42-.*\"}[$__range]) + increase(node_network_transmit_bytes_total{device=~\"dn42-.*\"}[$__range]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "External network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{device=\"eth0\"}[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{device=\"eth0\"}[$__rate_interval]))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "DN42 network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{device=~\"dn42-.*\"}[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{device=~\"dn42-.*\"}[$__rate_interval]))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "External network packets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_packets_total{device=\"eth0\"}[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(irate(node_network_transmit_packets_total{device=\"eth0\"}[$__rate_interval]))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "DN42 network packets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_packets_total{device=~\"dn42-.*\"}[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(irate(node_network_transmit_packets_total{device=~\"dn42-.*\"}[$__rate_interval]))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  { "title": "Routing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "BGP preferred routes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (bird_protocol_prefix_preferred_count{proto=\"BGP\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "BGP updates and withdraws received from DN42 peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "c/m" } },
   "targets": [
    {
     "expr": "sum(irate(bird_protocol_changes_update_import_receive_count{name=~\"dn42_.+\",proto=\"BGP\"}[$__rate_interval]))*60",
     "legendFormat": "Updates"
    },
    {
     "expr": "sum(irate(bird_protocol_changes_withdraw_import_receive_count{name=~\"dn42_.+\",proto=\"BGP\"}[$__rate_interval]))*60",
     "legendFormat": "Withdraws"
    }
   ]
  },
  {
   "title": "BGP updates and withdraws received from internal peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "c/m" } },
   "targets": [
    {
     "expr": "sum(irate(bird_protocol_changes_update_import_receive_count{name=~\"int_.+\",proto=\"BGP\"}[$__rate_interval]))*60",
     "legendFormat": "Updates"
    },
    {
     "expr": "sum(irate(bird_protocol_changes_withdraw_import_receive_count{name=~\"int_.+\",proto=\"BGP\"}[$__rate_interval]))*60",
     "legendFormat": "Withdraws"
    }
   ]
  },
  {
   "title": "DN42 ROA prefixes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (bird_protocol_prefix_preferred_count{name=~\"dn42_roa[46]\",proto=\"Static\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}