---

- name: install docker
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - python3-docker
    state: present
  register: install_docker

- name: remove br_netfilter kernel module
  modprobe:
    name: br_netfilter
    state: absent
  when: install_docker.changed

- name: copy docker daemon configuration
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  notify: restart docker
  tags: conf

- name: create general docker network
  docker_network:
    name: general
    enable_ipv6: yes
    ipam_config:
    - subnet: '{{ docker_net_v4 }}'
    - subnet: '{{ docker_net_v6 }}'
    driver_options:
      com.docker.network.bridge.name: dbr-general
