---

# This playbook installs HTTP ingresses, which serve static sites and
# reverse-proxy web applications.

- name: install public ingress
  gather_facts: no
  remote_user: '{{ admin_user }}'
  become: yes
  hosts: us-lga-bb-1.sesquialtera.dn42
  roles:
  - ingress
  vars:
    ingress_name: public
    ingress_caddyfile: public.Caddyfile.j2
  tags: ingress-public
