---

# This playbook installs Wireguard on backbone routers and generates a
# new public/private key pair if necessary. Newly generated public keys
# are printed at the end. These new public keys should then be copied to
# the appropriate wg_public_key host variables.

- name: install wireguard
  gather_facts: no
  remote_user: '{{ admin_user }}'
  become: yes
  hosts: backbones
  roles:
  - wg_base
