---

- name: create authoritative dns configuration and storage directories
  file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
  - /usr/local/etc/knot
  - /usr/local/lib/knot
  - /usr/local/lib/knot/zones

- name: copy knot configuration file
  template:
    src: knot.conf.j2
    dest: /usr/local/etc/knot/knot.conf
    owner: root
    group: root
    mode: '0644'
  notify: reload knot
  tags: conf

- name: copy zone files
  copy:
    src: '{{ item.file }}'
    dest: /usr/local/lib/knot/zones/
    owner: root
    group: root
    mode: '0644'
  notify: reload knot
  loop: '{{ adns_zones }}'
  tags: zones

- name: create and start knot container
  docker_container:
    name: adns
    image: cznic/knot:v3.2.1
    restart_policy: unless-stopped
    command: knotd
    volumes:
    - '/usr/local/etc/knot:/config'
    - '/usr/local/lib/knot:/storage'
    networks:
    - name: general
      ipv4_address: '{{ unicast_ips.adns[inventory_hostname].ipv4 }}'
      ipv6_address: '{{ unicast_ips.adns[inventory_hostname].ipv6 }}'
    networks_cli_compatible: yes
    network_mode: general
    container_default_behavior: no_defaults

- name: create and start knot service advertisement sidecar
  docker_container:
    name: adns-sa
    image: service-advertisement:20221012
    restart_policy: unless-stopped
    capabilities:
    - net_admin
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
    env:
      SA_LOCAL_AS: '4200000999'
      SA_NEIGHBOR: '{{ internal_ipv6 }}'
      SA_PEER_AS: '4200000998'
      SA_IPV4: '{{ adns_ipv4 }}'
      SA_IPV6: '{{ adns_ipv6 }}'
      SA_HEALTHCHECK_COMMAND: "dig +norec +short @:: {{ adns_healthcheck_zone }} ns | grep -v '^$' >/dev/null"
      SA_HEALTHCHECK_INTERVAL: '5'
      SA_HEALTHCHECK_TIMEOUT: '3'
      SA_HEALTHCHECK_MAX_FAIL_COUNT: '2'
    networks_cli_compatible: yes
    network_mode: container:adns
    container_default_behavior: no_defaults

- name: copy firewall rules for authoritative dns traffic
  template:
    src: adns.nft.j2
    dest: /etc/nftables/br-in.d/adns.nft
    owner: root
    group: root
    mode: '0644'
  notify: reload firewall
  tags: firewall
